# Redis related constants
ENVIRONMENT_VARIABLE_HOST = "TERASIM_REDIS_HOST"
ENVIRONMENT_VARIABLE_PORT = "TERASIM_REDIS_PORT"
ENVIRONMENT_VARIABLE_PASSWORD = "TERASIM_REDIS_PASSWORD"

# Redis channels or keys
CAV_COSIM_VEHICLE_INFO = "cav_cosim_vehicle_info"
TERASIM_COSIM_VEHICLE_INFO = "terasim_cosim_vehicle_info"
COSIM_TLS_INFO = "cosim_tls_info"

UPDATE_RATE_SET = 20
UPDATE_RATE_GET = 50
